version: "3.8"

name: defect-detector-services

services:
  clf-abp-path-analysis:
    build: .
    container_name: clf-abp-path-analysis
    ports:
      - "6300:6300"
    environment:
      # Flask Configuration
      FLASK_ENV: production
      FLASK_DEBUG: "False"
      PORT: 6300
    volumes:
      # MIDAS data volume mount - READ/WRITE for analysis outputs
      # For macOS - mount your local MIDAS directory
      # For Windows - change to: "C:/public/shared/DefectDetectorBuilds:/Users/ted.tedford/Documents/MIDAS"
      - "C:/Users/Public/MIDAS:/midas_data:ro"
    networks:
      - defectdetect-database_default
    restart: unless-stopped
    # Optional: If service needs to connect to database
    external_links:
      - mssql:mssql

networks:
  defectdetect-database_default:
    external: true
